/**
 * The policy tree a pull request carries, read WITHOUT a signature (ACP-442).
 *
 * `ziffer-scan --ci` runs on the customer's pull request, where the bundle is a
 * draft: its members are being edited, and the signature over them is made later,
 * in the publish job that holds the key. A reader that insisted on a current
 * signature would refuse every pull request before it graded anything, which is
 * the reason `ziffer decide --unsigned` exists (packages/mcp/src/decide.ts). This
 * is that path for the scan, and it is the ONLY place the scan reads a policy it
 * did not just sign itself; the name says so, and nothing outside `--ci` calls it.
 *
 * What it reads: the five members the engine's `decide` grades against
 * (`floors`, `risk_functions`, `reversibility`, `notice_targets`, `adapters`),
 * each validated against the engine's embedded schema before the engine sees it,
 * so a malformed member is refused by name (`BundleMemberInvalid`) exactly as the
 * scan refuses one it generated. Optionally `tool-names.json`, the scan's own
 * sidecar, when the tree was generated by a scan: it names the key each original
 * tool and server was given, collisions included.
 *
 * What it does NOT do: check `SIGNATURE`, the manifest's lifetime, the attesters,
 * the doors or the receipt identity. `--ci` prints that on its first line, every
 * run, so nobody reads a green job as "this bundle verifies".
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { SIDECAR } from '../bundle/generate.js';
import { validateMember } from '../bundle/schemas.js';
import type { Json } from '../wasm/json.js';
import { isJson, isRecord } from '../wasm/json.js';
import type { Policy } from '../wasm/ops.js';

/** A member the engine grades against is absent or is not JSON. */
export class PolicyTreeUnreadable extends Error {
  override readonly name = 'PolicyTreeUnreadable';
}

const GRADED: readonly (keyof Policy)[] = ['floors', 'risk_functions', 'reversibility', 'notice_targets', 'adapters'];

/** The scan's sidecar, when present: original names to the keys the bundle uses. */
export interface TreeNames {
  /** `JSON.stringify([server, tool])` -> key, as `bundle/names.ts`'s `toolId`. */
  tools: Map<string, string>;
  /** original server name -> key. */
  servers: Map<string, string>;
}

export interface UnsignedPolicyTree {
  dir: string;
  policy: Policy;
  /** `manifest.json`'s `tenant_id`, when the tree has a readable manifest. */
  tenantId: string | undefined;
  names: TreeNames | undefined;
}

function readJson(dir: string, path: string): Json {
  let text: string;
  try {
    text = readFileSync(join(dir, path), 'utf8');
  } catch (error) {
    const code = typeof error === 'object' && error !== null && 'code' in error ? String(error.code) : '';
    throw new PolicyTreeUnreadable(`${join(dir, path)}: ${code === 'ENOENT' ? 'absent' : code || 'unreadable'}`);
  }
  let v: unknown;
  try {
    v = JSON.parse(text);
  } catch (error) {
    throw new PolicyTreeUnreadable(`${join(dir, path)}: not JSON (${error instanceof Error ? error.message : String(error)})`);
  }
  if (!isJson(v)) throw new PolicyTreeUnreadable(`${join(dir, path)}: not JSON data`);
  return v;
}

function readOptional(dir: string, path: string): Json | undefined {
  try {
    return readJson(dir, path);
  } catch (error) {
    if (error instanceof PolicyTreeUnreadable && error.message.endsWith(': absent')) return undefined;
    throw error;
  }
}

function sidecarNames(v: Json | undefined): TreeNames | undefined {
  if (v === undefined || !isRecord(v)) return undefined;
  const tools = new Map<string, string>();
  const servers = new Map<string, string>();
  const list = v['tools'];
  if (Array.isArray(list)) {
    for (const t of list) {
      if (isRecord(t) && typeof t['server'] === 'string' && typeof t['tool'] === 'string' && typeof t['key'] === 'string') {
        tools.set(JSON.stringify([t['server'], t['tool']]), t['key']);
      }
    }
  }
  const map = v['servers'];
  if (isRecord(map)) for (const [original, key] of Object.entries(map)) if (typeof key === 'string') servers.set(original, key);
  return { tools, servers };
}

/** Read `dir` as a draft policy: the graded members, schema-checked, and no signature. */
export function loadPolicyTreeUnsigned(dir: string): UnsignedPolicyTree {
  const docs = new Map<keyof Policy, Json>();
  for (const m of GRADED) {
    const doc = readJson(dir, `${m}.json`);
    validateMember(`${m}.json`, doc);
    docs.set(m, doc);
  }
  const get = (m: keyof Policy): Json => {
    const d = docs.get(m);
    if (d === undefined) throw new PolicyTreeUnreadable(`${m}.json was not read`);
    return d;
  };
  const manifest = readOptional(dir, 'manifest.json');
  const tenant = manifest !== undefined && isRecord(manifest) ? manifest['tenant_id'] : undefined;
  return {
    dir,
    policy: {
      floors: get('floors'),
      risk_functions: get('risk_functions'),
      reversibility: get('reversibility'),
      notice_targets: get('notice_targets'),
      adapters: get('adapters'),
    },
    tenantId: typeof tenant === 'string' ? tenant : undefined,
    names: sidecarNames(readOptional(dir, SIDECAR)),
  };
}
