#!/usr/bin/env node
/**
 * Copy `docs/onboarding/sdk.md` into this package as a generated module, so the
 * built server carries the guide it serves (ACP-197, section 6b point 2:
 * "embedded at build -- the doc is the single source, the tool serves it").
 *
 * # Why embed rather than read the file at runtime
 *
 * `npx @ziffer-io/mcp` runs from a tarball in a temporary directory. There is no
 * `docs/` beside it and no repository root to walk up to, so a `readFile` of a
 * path relative to this module works in the checkout and fails in the only
 * deployment that matters. Embedding moves that failure from a developer's
 * machine to this script, which runs on every build.
 *
 * # Why this is not a second copy of the doc
 *
 * The generated file is gitignored and is rewritten by `pnpm build` before
 * `tsc` runs, so a stale one cannot be committed and cannot survive a build.
 * The check that makes that a control rather than an intention is in
 * `src/guide.test.ts`: it reads `docs/onboarding/sdk.md` from the repository
 * and asserts the served text equals what it extracts from THAT file. Edit the
 * doc without rebuilding and the test names the mismatch. This is the same
 * shape as `sdk/python/build.sh` copying the reference modules (runbook section
 * 4 point 3): build-time distribution of one source, not a fork of it.
 *
 * A missing or unmarked doc is a hard failure with a named reason. A build that
 * quietly produced an empty guide would ship a tool that answers every
 * integration question with nothing, which is worse than a build that stopped.
 *
 * # What it emits
 *
 * Three modules, not one, and the name of this script is now one artifact short
 * of what it does. `guide-source.ts` is the SDK guide above.
 * `repo-guide-source.ts` and `template-source.ts` are ACP-389's, and the second
 * half of this file explains them: the documents `get_policy_repo_guide` serves,
 * and the template bytes `check_policy_repo` compares a clone against.
 */

import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { exitIfPrebuilt } from '../../types/scripts/prebuilt.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(here, '..');
const repoRoot = resolve(packageRoot, '..', '..');
const source = join(repoRoot, 'docs', 'onboarding', 'sdk.md');
const outDir = join(packageRoot, 'src', 'generated');
const outFile = join(outDir, 'guide-source.ts');

// ACP-483: in the public source tree src/generated/ is committed and verified;
// most of what this script reads (docs/, services/, sdk/) is not there.
exitIfPrebuilt(repoRoot, 'packages/mcp', 'embed-guide');

/** The sections `get_integration_guide` serves. Kept in step with `SECTIONS`
 * in `src/guide.ts`: this script refuses a doc missing any of them, so the
 * extractor never has to handle an absent section at runtime. */
const REQUIRED = ['common', 'python', 'typescript'];

function fail(reason) {
  // Written to stderr and exits non-zero: a build step that reports a problem
  // on stdout and exits 0 is a build step that is not a gate.
  process.stderr.write(`embed-guide: ${reason}\n`);
  process.exit(1);
}

let markdown;
try {
  markdown = readFileSync(source, 'utf8');
} catch (error) {
  fail(
    `GuideSourceUnreadable: ${source}: ${error instanceof Error ? error.message : String(error)}\n` +
      '  This package embeds docs/onboarding/sdk.md at build time; without it there is no guide to serve.',
  );
}

for (const name of REQUIRED) {
  const open = `<!-- guide:${name} -->`;
  const close = `<!-- guide:/${name} -->`;
  const openAt = markdown.indexOf(open);
  const closeAt = markdown.indexOf(close);
  if (openAt === -1 || closeAt === -1) {
    fail(
      `GuideSectionMissing: ${source} has no ${openAt === -1 ? open : close} marker.\n` +
        '  get_integration_guide serves marked spans rather than headings, because a heading rename\n' +
        '  would silently change what the tool returns. Restore the marker or update SECTIONS in src/guide.ts.',
    );
  }
  if (closeAt < openAt) {
    fail(`GuideSectionMissing: ${source} closes guide:${name} before it opens it.`);
  }
}

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  '// GENERATED by scripts/embed-guide.mjs from docs/onboarding/sdk.md. Do not edit.\n' +
    '// Gitignored and rewritten on every build: see that script for why the doc is\n' +
    '// embedded rather than read from disk at runtime.\n' +
    `export const GUIDE_SOURCE_PATH = 'docs/onboarding/sdk.md';\n` +
    `export const GUIDE_MARKDOWN = ${JSON.stringify(markdown)};\n`,
  'utf8',
);
process.stderr.write(`embed-guide: ${markdown.length} bytes from docs/onboarding/sdk.md\n`);

// ---------------------------------------------------------------------------
// ACP-389: the policy repository's own three tools.
//
// Same argument as the guide above, one artifact over. `get_policy_repo_guide`
// serves two DOCUMENTS; `check_policy_repo` compares a customer's clone against
// the TEMPLATE WE SHIPPED, which means the published package has to carry those
// template bytes -- a check that reads `templates/policy-repo/` from a path
// relative to this module works in the checkout and finds nothing under `npx`.
// `explain_publish_failure` reads the publish workflow's own failure strings,
// so it needs the same bytes for a third reason.
//
// Everything below is EMBEDDED AND NOT TRANSCRIBED. No list of members, no
// filename and no refusal string is typed in this script: each is read out of
// the template, and a template that does not carry what the tools serve HALTS
// the build here with a named reason. That is the whole point of doing it at
// build time -- the alternative is a constant in a TypeScript file that agrees
// with the template on the day it is written.

/** The two documents `get_policy_repo_guide` serves, in the order it serves
 * them: what is in the repository first, then the hour around it. */
const REPO_GUIDE_DOCS = [
  join('templates', 'policy-repo', 'README.md'),
  join('docs', 'onboarding', 'start-here.md'),
];

/** Marked spans the repository guide must carry. `branch-protection` is the
 * one `check_policy_repo` SLICES rather than reads whole: RC-8 prints the
 * GitHub settings a person has to confirm, and it prints the README's, because
 * a second list of settings in TypeScript is the two-definitions defect with a
 * customer on the wrong side of it. */
const REPO_GUIDE_REQUIRED = ['branch-protection'];

/** The template root, and the files `check_policy_repo` compares byte for
 * byte. The three under `policy/` are the ones ZIFFER provisions: a clone that
 * still carries these bytes is still the demonstration tenant's, which is a
 * publish refused by name and a wasted afternoon (the template's README says
 * so in as many words). */
const TEMPLATE_ROOT = join('templates', 'policy-repo');
const WORKFLOW_DIR = join('.github', 'workflows');

/** Every workflow the template ships, READ FROM ITS FOLDER and never typed
 * (ACP-480). The list was typed, the template gained policy-scan.yml with
 * ACP-442, and for as long as nobody retyped it `check_policy_repo` passed a
 * clone whose scan workflow was changed or deleted, without a word about it.
 * An empty or unreadable folder halts: a comparison derived from an empty set
 * passes by having nothing to compare. An entry that is not a `*.yml` file
 * halts too, because a workflow GitHub would run and this list would skip is
 * the same silence with a different spelling. */
function workflowFiles() {
  const relative = join(TEMPLATE_ROOT, WORKFLOW_DIR);
  const dir = join(repoRoot, relative);
  let entries;
  try {
    entries = readdirSync(dir).sort();
  } catch (error) {
    fail(
      `TemplateWorkflowsUnreadable: ${relative}: ${error instanceof Error ? error.message : String(error)}\n` +
        '  check_policy_repo compares a clone against every workflow in that folder; with no\n' +
        '  folder to read it would have nothing to compare.',
    );
    return [];
  }
  const out = [];
  for (const entry of entries) {
    if (!entry.endsWith('.yml') || !statSync(join(dir, entry)).isFile()) {
      fail(
        `TemplateWorkflowUnrecognised: ${relative}/${entry} is not a *.yml file.\n` +
          '  Every entry in that folder is compared or the build halts; none is skipped.',
      );
    }
    out.push(join(WORKFLOW_DIR, entry));
  }
  if (out.length === 0) {
    fail(
      `TemplateWorkflowsEmpty: ${relative} holds no workflow.\n` +
        '  A workflow check derived from an empty set passes by having nothing to check.',
    );
  }
  return out;
}

const WORKFLOW_FILES = workflowFiles();
/** The three members ZIFFER provisions. */
const PROVISIONED_FILES = [
  join('policy', 'attesters', 'registry.json'),
  join('policy', 'door_identities.json'),
  join('policy', 'receipt_identity.json'),
];
const TEMPLATE_FILES = [...WORKFLOW_FILES, ...PROVISIONED_FILES, '.gitignore'];

function readSource(relative) {
  const absolute = join(repoRoot, relative);
  try {
    return readFileSync(absolute, 'utf8');
  } catch (error) {
    fail(
      `TemplateSourceUnreadable: ${relative}: ${error instanceof Error ? error.message : String(error)}\n` +
        '  packages/mcp embeds it at build time; without it check_policy_repo has nothing to\n' +
        '  compare a clone against and would have to pass by having nothing to say.',
    );
    return '';
  }
}

/** Every file under `policy/` except `examples/`, relative to `policy/`. This
 * is the bundle's member set, WALKED rather than listed: the ticket called it
 * "the ten policy files" and the template ships eleven, which is exactly what a
 * typed count does. */
function policyMembers() {
  const root = join(repoRoot, TEMPLATE_ROOT, 'policy');
  const out = [];
  const walk = (dir, prefix) => {
    let entries;
    try {
      entries = readdirSync(dir).sort();
    } catch (error) {
      fail(`TemplateSourceUnreadable: ${dir}: ${error instanceof Error ? error.message : String(error)}`);
      return;
    }
    for (const entry of entries) {
      const relative = prefix === '' ? entry : `${prefix}/${entry}`;
      if (relative === 'examples') continue; // graded proposals, not members
      const absolute = join(dir, entry);
      if (statSync(absolute).isDirectory()) walk(absolute, relative);
      else out.push(relative);
    }
  };
  walk(root, '');
  if (out.length === 0) {
    fail(
      `TemplateMembersEmpty: ${TEMPLATE_ROOT}/policy holds no members.\n` +
        '  A member check derived from an empty set passes by having nothing to check.',
    );
  }
  return out;
}

/** The two key filenames, read out of `bin/new-signing-key.sh` rather than
 * typed here. That script is the one command a customer runs to make the pair,
 * so it is the only place that knows what the files are called; a copy in this
 * package would be the name that stops moving when the script's does. */
function keyFileNames() {
  const relative = join(TEMPLATE_ROOT, 'bin', 'new-signing-key.sh');
  const script = readSource(relative);
  const pub = /^PUB="([^"]+)"$/m.exec(script);
  const out = /^OUT="([^"]+)"$/m.exec(script);
  if (pub === null || out === null) {
    fail(
      `KeyFileNamesUnreadable: ${relative} no longer assigns ${pub === null ? 'PUB' : 'OUT'} as a plain quoted literal.\n` +
        '  check_policy_repo derives the committed public key\'s name and the private key\'s name\n' +
        '  from that script. Typing them here instead would be a second definition of the pair.',
    );
  }
  const privatePath = out[1];
  const privateName = privatePath.slice(privatePath.lastIndexOf('/') + 1);
  if (!privateName.includes('.')) {
    fail(`KeyFileNamesUnreadable: OUT=${privatePath} has no filename to derive a pattern from.`);
  }
  return { publicName: pub[1], privatePath, privateName };
}

// --- the guide ------------------------------------------------------------

const repoGuide = REPO_GUIDE_DOCS.map((relative) => ({
  path: relative.split('\\').join('/'),
  markdown: readSource(relative),
}));

for (const doc of repoGuide) {
  if (doc.markdown.trim() === '') {
    fail(`GuideSourceEmpty: ${doc.path} is empty, so the tool would serve nothing and read as an answer.`);
  }
}

for (const name of REPO_GUIDE_REQUIRED) {
  const open = `<!-- guide:${name} -->`;
  const close = `<!-- guide:/${name} -->`;
  const carried = repoGuide.filter(
    (doc) => doc.markdown.indexOf(open) !== -1 && doc.markdown.indexOf(close) > doc.markdown.indexOf(open),
  );
  if (carried.length !== 1) {
    fail(
      `GuideSectionMissing: exactly one of ${REPO_GUIDE_DOCS.join(', ')} must carry a complete ` +
        `guide:${name} span; ${carried.length} do.\n` +
        '  check_policy_repo slices that span instead of restating it. Restore the markers, or\n' +
        '  change REPO_GUIDE_REQUIRED here and the reader in src/repo-guide.ts together.',
    );
  }
}

writeFileSync(
  join(outDir, 'repo-guide-source.ts'),
  '// GENERATED by scripts/embed-guide.mjs. Do not edit.\n' +
    '// The documents get_policy_repo_guide serves, in the order it serves them.\n' +
    'export interface RepoGuideDoc { readonly path: string; readonly markdown: string }\n' +
    `export const REPO_GUIDE_DOCS: readonly RepoGuideDoc[] = ${JSON.stringify(repoGuide)};\n` +
    `export const REPO_GUIDE_REQUIRED_SPANS: readonly string[] = ${JSON.stringify(REPO_GUIDE_REQUIRED)};\n`,
  'utf8',
);

// --- the template ---------------------------------------------------------

const members = policyMembers();
const keys = keyFileNames();
const templateFiles = {};
for (const relative of TEMPLATE_FILES) {
  const posix = relative.split('\\').join('/');
  templateFiles[posix] = readSource(join(TEMPLATE_ROOT, relative));
  if (templateFiles[posix] === '') {
    fail(`TemplateSourceEmpty: ${TEMPLATE_ROOT}/${posix} is empty; a byte comparison against it proves nothing.`);
  }
}

const posix = (p) => p.split('\\').join('/');

/**
 * ACP-482. Where the one permitted edit sits in each shipped workflow, READ
 * from the workflow itself: its `POLICY_DIR:` entry and, where it has one, the
 * `paths:` filter GitHub reads before any `env:` exists. `check_policy_repo`
 * holds a customer's copy equal to the shipped bytes everywhere except these
 * slots, so a typed list of line numbers here would be the copy that drifts the
 * first time a header comment grows a line. A workflow with no POLICY_DIR this
 * reading can find HALTS the build by name: the comparison would otherwise fall
 * back to byte-for-byte for that file and fail every customer who made the edit
 * its own header invites.
 *
 * A slot is the text before the folder and the text after it on its line. For
 * POLICY_DIR the folder is the whole value (`policy/`); for `paths:` it is the
 * glob without its `/**`, which is fixed text, so `rules/**` gives `rules`.
 */
const POLICY_DIR_SLOT = /^(\s*POLICY_DIR:[ \t]*)(\S+?)([ \t]*)$/;
const PATHS_SLOT = /^(\s*paths:\s*\[\s*')([^']*?)(\/\*\*'\s*\]\s*)$/;
const normalFolder = (value) => {
  let v = value;
  if (v.endsWith('/**')) v = v.slice(0, -3);
  if (v.endsWith('/')) v = v.slice(0, -1);
  return v;
};
const TEMPLATE_POLICY_FOLDER = 'policy';
const policySlots = {};
for (const relative of WORKFLOW_FILES.map(posix)) {
  const text = templateFiles[relative];
  const slots = [];
  text.split('\n').forEach((line, index) => {
    const dir = POLICY_DIR_SLOT.exec(line);
    if (dir !== null) {
      slots.push({ line: index + 1, kind: 'POLICY_DIR', prefix: dir[1], suffix: dir[3], value: normalFolder(dir[2]) });
      return;
    }
    if (/^\s*paths:/.test(line)) {
      const filter = PATHS_SLOT.exec(line);
      if (filter === null) {
        fail(
          `TemplateWorkflowPathsUnreadable: ${TEMPLATE_ROOT}/${relative} line ${index + 1} is a paths: filter\n` +
            "  that is not [ '<folder>/**' ], so the folder in it cannot be found and compared.",
        );
      }
      slots.push({ line: index + 1, kind: 'paths', prefix: filter[1], suffix: filter[3], value: normalFolder(filter[2]) });
    }
  });
  const dirs = slots.filter((slot) => slot.kind === 'POLICY_DIR');
  if (dirs.length !== 1) {
    fail(
      `TemplateWorkflowPolicyDirAbsent: ${TEMPLATE_ROOT}/${relative} sets POLICY_DIR ${dirs.length} times, not once.\n` +
        '  check_policy_repo lets a customer change that one value and nothing else; with no\n' +
        '  single POLICY_DIR to find it would refuse the edit the header invites.',
    );
  }
  for (const slot of slots) {
    if (slot.value !== TEMPLATE_POLICY_FOLDER) {
      fail(
        `TemplatePolicyFolderDisagrees: ${TEMPLATE_ROOT}/${relative} line ${slot.line} names ${slot.value}/,\n` +
          `  and the template's bundle lives in ${TEMPLATE_POLICY_FOLDER}/.`,
      );
    }
  }
  policySlots[relative] = slots.map(({ line, kind, prefix, suffix }) => ({ line, kind, prefix, suffix }));
}

/**
 * ACP-482, the second permitted value: NO_EXAMPLE_PROPOSALS, which the validate
 * workflow's header invites a customer to set when they have no example
 * proposals. Read the same way as the folder: the file that sets it, the line,
 * the text around the value. The values it may take are the ones the workflow's
 * own `case` accepts, and the one that means "we have none" is the one its own
 * `if [ ... = <value> ]` tests, so neither is typed here. It must be set exactly
 * once, in exactly one workflow, or the build halts by name.
 */
const NO_EXAMPLES_SLOT_RE = /^(\s*NO_EXAMPLE_PROPOSALS:[ \t]*)(\S+?)([ \t]*)$/;
let noExamples = null;
for (const relative of WORKFLOW_FILES.map(posix)) {
  const text = templateFiles[relative];
  const lines = text.split('\n');
  const hits = [];
  lines.forEach((line, index) => {
    const m = NO_EXAMPLES_SLOT_RE.exec(line);
    if (m !== null) hits.push({ line: index + 1, prefix: m[1], suffix: m[3], value: m[2] });
  });
  if (hits.length === 0) continue;
  if (hits.length !== 1 || noExamples !== null) {
    fail(
      `TemplateNoExampleProposalsRepeated: NO_EXAMPLE_PROPOSALS is set more than once across ${TEMPLATE_ROOT}/.github/workflows;\n` +
        '  check_policy_repo permits exactly one such value and could not say which is the one.',
    );
  }
  const accepted = /case "\$NO_EXAMPLE_PROPOSALS" in\s*\n\s*([A-Za-z0-9_|]+)\)\s*;;/.exec(text);
  const none = /if \[ "\$NO_EXAMPLE_PROPOSALS" = ([A-Za-z0-9_]+) \]/.exec(text);
  if (accepted === null || none === null) {
    fail(
      `TemplateNoExampleProposalsUnreadable: ${TEMPLATE_ROOT}/${relative} sets NO_EXAMPLE_PROPOSALS but its values\n` +
        '  (the `case` that accepts them, the `if [ ... = <value> ]` that means "none") cannot be read.',
    );
  }
  const values = accepted[1].split('|');
  const shipped = hits[0].value.replace(/^'(.*)'$/, '$1').replace(/^"(.*)"$/, '$1');
  if (!values.includes(none[1]) || !values.includes(shipped)) {
    fail(
      `TemplateNoExampleProposalsDisagrees: ${TEMPLATE_ROOT}/${relative} accepts ${values.join(', ')}, ships ${shipped}\n` +
        `  and tests for ${none[1]}; each must be one of the accepted values.`,
    );
  }
  noExamples = { file: relative, line: hits[0].line, prefix: hits[0].prefix, suffix: hits[0].suffix, values, none: none[1], shipped };
}
if (noExamples === null) {
  fail(
    `TemplateNoExampleProposalsAbsent: no workflow under ${TEMPLATE_ROOT}/.github/workflows sets NO_EXAMPLE_PROPOSALS.\n` +
      '  check_policy_repo reads it to grade examples the way the validate workflow does.',
  );
}

writeFileSync(
  join(outDir, 'template-source.ts'),
  '// GENERATED by scripts/embed-guide.mjs from templates/policy-repo. Do not edit.\n' +
    '// Gitignored and rewritten on every build; src/repo-check.test.ts asserts these\n' +
    '// bytes are still the template on disk, so a stale copy cannot survive a run.\n' +
    `export const TEMPLATE_ROOT = ${JSON.stringify(posix(TEMPLATE_ROOT))};\n` +
    `export const TEMPLATE_FILES: Readonly<Record<string, string>> = ${JSON.stringify(templateFiles)};\n` +
    `export const WORKFLOW_FILES: readonly string[] = ${JSON.stringify(WORKFLOW_FILES.map(posix))};\n` +
    `export const PROVISIONED_FILES: readonly string[] = ${JSON.stringify(PROVISIONED_FILES.map(posix))};\n` +
    `export const POLICY_MEMBERS: readonly string[] = ${JSON.stringify(members)};\n` +
    `export const PUBLIC_KEY_NAME = ${JSON.stringify(keys.publicName)};\n` +
    `export const PRIVATE_KEY_NAME = ${JSON.stringify(keys.privateName)};\n` +
    `export const PRIVATE_KEY_PATH = ${JSON.stringify(keys.privatePath)};\n` +
    '/** One place a workflow names the policy folder: the text before and after it on its line. */\n' +
    "export interface PolicyDirSlot { readonly line: number; readonly kind: 'POLICY_DIR' | 'paths'; readonly prefix: string; readonly suffix: string }\n" +
    `export const SHIPPED_POLICY_FOLDER = ${JSON.stringify(TEMPLATE_POLICY_FOLDER)};\n` +
    `export const WORKFLOW_POLICY_SLOTS: Readonly<Record<string, readonly PolicyDirSlot[]>> = ${JSON.stringify(policySlots)};\n` +
    '/** Where the validate workflow sets NO_EXAMPLE_PROPOSALS, the values its own `case` accepts, the one meaning "none", and the shipped one. */\n' +
    'export interface NoExamplesSlot { readonly file: string; readonly line: number; readonly prefix: string; readonly suffix: string; readonly values: readonly string[]; readonly none: string; readonly shipped: string }\n' +
    `export const NO_EXAMPLES_SLOT: NoExamplesSlot = ${JSON.stringify(noExamples)};\n`,
  'utf8',
);

process.stderr.write(
  `embed-guide: ${repoGuide.length} repository documents, ${TEMPLATE_FILES.length} template files, ` +
    `${members.length} bundle members, public key ${keys.publicName}\n`,
);

// ---------------------------------------------------------------------------
// ACP-390: what `get_started` says, and what `lint_proposal` validates against.
//
// Same argument a third and fourth time. `get_started` names the version a
// developer is told to install and the four variables they have to set, and
// `lint_proposal` grades a proposal against the wire schema -- and every one of
// those is a fact that already exists somewhere in this repository. Not one of
// them is typed below: the versions are READ out of the manifests that publish
// them, the four variables' table is SLICED out of this package's own README,
// the six-line wrap is SLICED out of the guide, and the schema set is WALKED
// from `wire/proposal.schema.json`'s own `$ref`s. A constant here would be a
// second statement of each, and the one that goes stale is always the copy.

/** The manifests the published versions come from, and how to read each. The
 * pair is the point: a developer installing the Python package and a developer
 * installing the TypeScript one must be sent to the same release, and the only
 * way to say that is to read both numbers rather than write one. */
const PINNED = [
  { language: 'python', manifest: join('sdk', 'python', 'pyproject.toml') },
  { language: 'typescript', manifest: join('packages', 'acp-client', 'package.json') },
];

/** `version = "x.y.z"` in a `[project]` table. Deliberately not a TOML parser:
 * one line is read, it is asserted to be a plain quoted literal, and anything
 * else HALTS rather than being guessed at -- a build that guessed would print
 * an install command for a version nobody published. */
function pythonVersion(relative) {
  const found = /^version\s*=\s*"([^"]+)"$/m.exec(readSource(relative));
  if (found === null) {
    fail(
      `PinnedVersionUnreadable: ${relative} no longer assigns version as a plain quoted literal.\n` +
        '  get_started prints the install command at the PINNED version and reads it here. Typing\n' +
        '  a number into the MCP package instead would be a second statement of what we published.',
    );
  }
  return found[1];
}

function npmPackage(relative) {
  let doc;
  try {
    doc = JSON.parse(readSource(relative));
  } catch (error) {
    fail(`PinnedVersionUnreadable: ${relative}: ${error instanceof Error ? error.message : String(error)}`);
  }
  if (typeof doc.name !== 'string' || typeof doc.version !== 'string') {
    fail(`PinnedVersionUnreadable: ${relative} carries no string name/version pair.`);
  }
  return { name: doc.name, version: doc.version };
}

const python = pythonVersion(PINNED[0].manifest);
const client = npmPackage(PINNED[1].manifest);
const verify = npmPackage(join('packages', 'acp-verify', 'package.json'));

/** The distribution NAMES an integration imports, read from the manifests that
 * publish them. `check_integration` decides whether a file has anything to do
 * with ZIFFER by looking for one of these, and a name typed into that module
 * would be a second statement of what we publish -- the copy that keeps the old
 * spelling through a rename, which is exactly the failure
 * `tools/check-org-name.py` exists for one organisation up. */
function pythonName(relative) {
  const found = /^name\s*=\s*"([^"]+)"$/m.exec(readSource(relative));
  if (found === null) {
    fail(`PinnedVersionUnreadable: ${relative} no longer assigns name as a plain quoted literal.`);
  }
  return found[1];
}
const PACKAGES = {
  python: pythonName(PINNED[0].manifest),
  client: client.name,
  verify: verify.name,
};

/** The two installs, each naming the manifest it was read from so the served
 * text can be traced back without grepping. The COMMAND shape is this file's
 * (it is not written down anywhere else); every value in it is read. */
const INSTALLS = [
  {
    language: 'python',
    command: `pip install ziffer==${python}`,
    source: posix(PINNED[0].manifest),
  },
  {
    language: 'typescript',
    command: `npm install ${client.name}@${client.version}`,
    source: posix(PINNED[1].manifest),
  },
];

/** Where the two prose blocks `get_started` serves come from, by span. Both
 * are SLICED and neither is restated: `six-line-wrap` is the shape of the
 * change as `sdk.md` section 4 draws it, and `configuration` is the four
 * variables and where each comes from, out of this package's own README --
 * which is the table a developer reading the npm page already sees. */
const STARTED_SPANS = [
  { name: 'six-line-wrap', path: join('docs', 'onboarding', 'sdk.md') },
  { name: 'configuration', path: join('packages', 'mcp', 'README.md') },
];

const startedSpans = STARTED_SPANS.map(({ name, path }) => {
  const markdown = readSource(path);
  const open = `<!-- guide:${name} -->`;
  const close = `<!-- guide:/${name} -->`;
  const openAt = markdown.indexOf(open);
  const closeAt = markdown.indexOf(close);
  if (openAt === -1 || closeAt <= openAt) {
    fail(
      `GuideSectionMissing: ${posix(path)} carries no complete guide:${name} span.\n` +
        '  get_started SLICES that span rather than restating it, so a lost marker must stop the\n' +
        '  build instead of producing a tool that answers with one section missing.',
    );
  }
  const text = markdown.slice(openAt + open.length, closeAt).trim();
  if (text === '') {
    fail(`GuideSectionMissing: ${posix(path)}'s guide:${name} span is empty, so the tool would serve nothing.`);
  }
  return { name, path: posix(path), markdown: text };
});

/** Where a developer is sent to GET an account. A real one: the first-hour
 * guide, which is already embedded above for `get_policy_repo_guide`. Named
 * here by path so the two readers agree, and asserted to be one of them. */
const START_HERE = posix(join('docs', 'onboarding', 'start-here.md'));
if (!repoGuide.some((doc) => doc.path === START_HERE)) {
  fail(
    `StartHereNotEmbedded: ${START_HERE} is not among the documents this script embeds.\n` +
      '  get_started points a developer at it for real account creation, and a pointer at a\n' +
      '  document the package does not carry is a pointer at nothing.',
  );
}

writeFileSync(
  join(outDir, 'started-source.ts'),
  '// GENERATED by scripts/embed-guide.mjs. Do not edit.\n' +
    '// The pinned install commands, the two sliced spans, and where an account comes from.\n' +
    'export interface Install { readonly language: string; readonly command: string; readonly source: string }\n' +
    'export interface StartedSpan { readonly name: string; readonly path: string; readonly markdown: string }\n' +
    `export const INSTALLS: readonly Install[] = ${JSON.stringify(INSTALLS)};\n` +
    `export const STARTED_SPANS: readonly StartedSpan[] = ${JSON.stringify(startedSpans)};\n` +
    `export const START_HERE_PATH = ${JSON.stringify(START_HERE)};\n` +
    'export interface Packages { readonly python: string; readonly client: string; readonly verify: string }\n' +
    `export const PACKAGES: Packages = ${JSON.stringify(PACKAGES)};\n`,
  'utf8',
);

// --- the wire Proposal schema ---------------------------------------------
//
// WALKED FROM ONE ENTRY POINT, never listed. `lint_proposal` validates against
// `wire/proposal.schema.json`, which `$ref`s into three other vendored schemas;
// a typed list of four filenames here would be right until a `$ref` moved. The
// closure below follows the refs the schema actually has and HALTS on one that
// resolves to nothing, which is the case a list could not have seen at all.

const SCHEMA_ROOT = join('services', 'validator', 'schemas');
const PROPOSAL_SCHEMA = 'wire/proposal.schema.json';

function loadSchemas() {
  const root = join(repoRoot, SCHEMA_ROOT);
  const byPath = {};
  const byId = {};
  const walk = (dir, prefix) => {
    let entries;
    try {
      entries = readdirSync(dir).sort();
    } catch (error) {
      fail(`SchemaSourceUnreadable: ${dir}: ${error instanceof Error ? error.message : String(error)}`);
      return;
    }
    for (const entry of entries) {
      const relative = prefix === '' ? entry : `${prefix}/${entry}`;
      const absolute = join(dir, entry);
      if (statSync(absolute).isDirectory()) {
        walk(absolute, relative);
      } else if (entry.endsWith('.schema.json')) {
        let doc;
        try {
          doc = JSON.parse(readFileSync(absolute, 'utf8'));
        } catch (error) {
          fail(`SchemaSourceUnreadable: ${relative}: ${error instanceof Error ? error.message : String(error)}`);
          return;
        }
        byPath[relative] = doc;
        if (typeof doc.$id === 'string') byId[doc.$id] = relative;
      }
    }
  };
  walk(root, '');
  return { byPath, byId };
}

const { byPath: allSchemas, byId: schemaIds } = loadSchemas();
if (allSchemas[PROPOSAL_SCHEMA] === undefined) {
  fail(
    `SchemaSourceUnreadable: ${SCHEMA_ROOT}/${PROPOSAL_SCHEMA} is not there.\n` +
      '  lint_proposal has nothing to validate against without it, and a linter with no schema\n' +
      '  would pass every proposal by having no rule to apply.',
  );
}

/**
 * Walk the REACHABLE schema graph from the Proposal, collecting the documents a
 * `$ref` leaves this one for and the keywords the reachable nodes actually use.
 *
 * SCHEMA-AWARE, and the first draft was not. A walk that treats every object key
 * as a keyword counts `schema_id` and `tenant_id` -- property NAMES -- as
 * constraints, and a walk that follows every `$ref` in a whole document drags in
 * the refs of `$defs` nobody reaches: the first version of this collected 106
 * "keywords" across 8 documents where the reachable answer is 21 across 4. Both
 * numbers would have been asserted against, and the assertion would have been
 * about a graph the linter never visits. So the recursion below descends only
 * through the positions that hold a SCHEMA, and a keyword is a key of one.
 */
function pointer(doc, ref, relative) {
  const [base, fragment] = ref.split('#');
  const target = base === '' ? relative : schemaIds[base];
  if (target === undefined) {
    fail(
      `SchemaRefUnresolvable: ${relative} refs ${ref}, and no schema under ${SCHEMA_ROOT} declares that $id.\n` +
        '  The closure is WALKED from the Proposal schema rather than listed, so an unresolvable\n' +
        '  ref has to stop the build: shipping it would give lint_proposal a rule it cannot apply\n' +
        '  and a field it would report as valid by never having looked at it.',
    );
    return null;
  }
  const targetDoc = base === '' ? doc : allSchemas[target];
  if (targetDoc === undefined) {
    fail(`SchemaSourceUnreadable: ${SCHEMA_ROOT}/${target} is reached by a $ref and is not there.`);
    return null;
  }
  let node = targetDoc;
  for (const part of (fragment ?? '').split('/').filter((p) => p !== '')) {
    if (typeof node !== 'object' || node === null || node[part] === undefined) {
      fail(`SchemaRefUnresolvable: ${relative} refs ${ref}, which points at nothing.`);
      return null;
    }
    node = node[part];
  }
  return { node, doc: targetDoc, relative: target };
}

const closure = {};
const keywords = new Set();
const seen = new Set();

/** One schema node. `relative` is the document it lives in, which is what its
 * own local `$ref`s resolve against. */
function walkSchema(node, doc, relative) {
  if (typeof node !== 'object' || node === null || Array.isArray(node)) return;
  for (const key of Object.keys(node)) keywords.add(key);
  closure[relative] = doc;

  if (typeof node.$ref === 'string') {
    if (seen.has(`${relative}|${node.$ref}`)) return;
    seen.add(`${relative}|${node.$ref}`);
    const resolved = pointer(doc, node.$ref, relative);
    if (resolved !== null) walkSchema(resolved.node, resolved.doc, resolved.relative);
    return;
  }
  for (const key of ['items', 'propertyNames', 'additionalProperties', 'not']) {
    if (typeof node[key] === 'object' && node[key] !== null) walkSchema(node[key], doc, relative);
  }
  for (const key of ['properties', '$defs', 'definitions', 'patternProperties']) {
    const table = node[key];
    if (typeof table === 'object' && table !== null) {
      // A `$defs` TABLE on a node this walk reached is walked whole -- a def
      // nobody refs is still shipped in the embedded document, and a keyword in
      // it is one the linter would meet the day a ref reached it. A `$ref` INTO
      // another document still enters at the one def it names, so this does not
      // drag a whole foreign schema in behind one scalar.
      for (const value of Object.values(table)) walkSchema(value, doc, relative);
    }
  }
  for (const key of ['oneOf', 'anyOf', 'allOf', 'prefixItems']) {
    if (Array.isArray(node[key])) for (const item of node[key]) walkSchema(item, doc, relative);
  }
}

walkSchema(allSchemas[PROPOSAL_SCHEMA], allSchemas[PROPOSAL_SCHEMA], PROPOSAL_SCHEMA);

writeFileSync(
  join(outDir, 'schema-source.ts'),
  '// GENERATED by scripts/embed-guide.mjs from services/validator/schemas. Do not edit.\n' +
    '// The wire Proposal schema and the transitive closure of its $refs, walked.\n' +
    `export const SCHEMA_ROOT = ${JSON.stringify(posix(SCHEMA_ROOT))};\n` +
    `export const PROPOSAL_SCHEMA = ${JSON.stringify(PROPOSAL_SCHEMA)};\n` +
    '// eslint-disable-next-line -- a JSON document is `unknown` to this package; the reader narrows it.\n' +
    `export const SCHEMAS: Readonly<Record<string, unknown>> = ${JSON.stringify(closure)};\n` +
    '/** Every keyword the closure above uses. `proposal-lint.ts` is asserted to implement\n' +
    ' * or deliberately ignore each one, so a schema edit that introduces a keyword the\n' +
    ' * reader does not know is a red test rather than a constraint nobody applied. */\n' +
    `export const SCHEMA_KEYWORDS: readonly string[] = ${JSON.stringify([...keywords].sort())};\n`,
  'utf8',
);

process.stderr.write(
  `embed-guide: ${PACKAGES.python} ${python}, ${client.name} ${client.version}, ` +
    `${startedSpans.length} started spans, ` +
    `${Object.keys(closure).length} schemas, ${keywords.size} keywords\n`,
);

// ---------------------------------------------------------------------------
// ACP-392: the onboarding corpus, and the refusal names this product emits.
//
// Same argument as everything above, one directory wider. `search_docs` reads
// EVERY customer-facing onboarding document, and `explain_refusal` reads the
// refusal table inside one of them; both run from a tarball under `npx`, where
// there is no `docs/` beside the module and no repository root to walk up to.
//
// TWO THINGS ARE WALKED RATHER THAN LISTED, and both were listed first in the
// drafting of this slice:
//
//   * the DOCUMENTS. `docs/onboarding/*.md` is read from the directory, so a
//     document added there is served without this file being edited. What IS
//     written here is the opposite -- the documents deliberately NOT served --
//     because a published npm package is the wrong place to discover that a
//     directory gained an internal artifact. The exclusion is pinned BY NAME
//     with its reason, and a pin naming a file that is no longer there HALTS
//     the build: a pin that has stopped firing is a claim nobody is checking
//     (ACP-299's rule).
//   * the REFUSAL NAMES. They are read out of the Rust that emits them -- the
//     gateway's `error_name` module and the Policy Engine's `clause` module
//     and attestation refusals -- and a source that yields NONE halts the
//     build. `explain_refusal` can then say "this is a real name we emit and
//     the support table has no row for it" rather than guessing, and
//     `refusals.test.ts` derives the same set independently off disk.

const ONBOARDING_DIR = join('docs', 'onboarding');

/**
 * The documents under `docs/onboarding/` that are NOT served, by filename,
 * each with the reason it is withheld.
 *
 * THE REASON IS WRITTEN ONCE, in the entry's value, and nowhere else in prose:
 * `docs.test.ts` asserts that `packages/mcp/README.md` neither names a withheld
 * document nor quotes its reason. `search_docs` answers into a customer's coding
 * agent, which is why build state stays out of it for as long as the package is
 * installed -- and why the pin, not a deleted file, is the switch.
 *
 * THE VALUE IS COMPILED INTO THE PUBLISHED PACKAGE (dist/generated/docs-source.js),
 * so it is customer text: it says what the document is, states no gap, and names
 * no ticket and no path of this repository. What the maintainers need stays in
 * this comment: the journey sheet is the team's working record of the onboarding
 * build, and the pin is reversible -- delete the entry and the next build serves
 * the document.
 */
const ONBOARDING_NOT_SERVED = {
  'journey-sheet-2026-09-15.md':
    'withheld: a working record kept by the team that runs ZIFFER, not a guide. ' +
    "It answers no question a developer asks while integrating.",
};

/** Every `*.md` in `docs/onboarding/`, sorted, minus the withheld ones. */
function onboardingDocs() {
  const dir = join(repoRoot, ONBOARDING_DIR);
  let entries;
  try {
    entries = readdirSync(dir).sort();
  } catch (error) {
    fail(
      `OnboardingDirUnreadable: ${ONBOARDING_DIR}: ${error instanceof Error ? error.message : String(error)}\n` +
        '  search_docs serves this directory; without it the tool would answer every question\n' +
        '  with nothing, which reads as an answer.',
    );
    return [];
  }
  const markdown = entries.filter((name) => name.endsWith('.md'));
  for (const withheld of Object.keys(ONBOARDING_NOT_SERVED)) {
    if (!markdown.includes(withheld)) {
      fail(
        `WithheldDocumentAbsent: ${ONBOARDING_DIR}/${withheld} is pinned as not-served and is not there.\n` +
          '  A pin that has stopped firing is a claim nobody is checking. Either the file moved and\n' +
          '  the pin moves with it, or it is gone and the entry goes from ONBOARDING_NOT_SERVED.',
      );
    }
  }
  const served = markdown.filter((name) => !(name in ONBOARDING_NOT_SERVED));
  if (served.length === 0) {
    fail(`OnboardingDirEmpty: ${ONBOARDING_DIR} yielded no document to serve.`);
  }
  return served.map((name) => {
    const relative = `${ONBOARDING_DIR}/${name}`.split('\\').join('/');
    const text = readSource(relative);
    if (text.trim() === '') {
      fail(`OnboardingDocEmpty: ${relative} is empty, so search_docs would rank nothing from it.`);
    }
    return { path: relative, markdown: text };
  });
}

/** `docs/onboarding/support.md` and the marker that opens its refusal table.
 *
 * The marker is the document saying "the table below is the one a checker
 * reads", in its own bytes; `tools/check-support-doc.py` reads the same one.
 * It is a MARKER and not a heading for `guide.ts`'s reason -- renaming a
 * heading is an editorial act that should not silently change what a tool
 * returns. */
const SUPPORT_DOC = `${ONBOARDING_DIR}/support.md`.split('\\').join('/');
const REFUSAL_TABLE_MARKER = '<!-- support:refusal-table -->';

/**
 * Where refusal names are MINTED, and how to read each one out.
 *
 * Read rather than transcribed, `FAILURE_KEYS`'s rule one tool over: a list of
 * refusal names typed into TypeScript agrees with the services on the day it
 * is written. A source that yields no name at all halts the build, because an
 * empty emitter set makes every completeness comparison downstream pass by
 * having nothing to compare.
 */
const REFUSAL_EMITTERS = [
  {
    path: 'services/gateway/src/gateway.rs',
    origin: 'the ZIFFER API',
    what: 'the names the public API answers with, under `pub mod error_name`',
    // `pub const NAME: &str = "Spelling";` inside `pub mod error_name { ... }`.
    read: (text) => constsInModule(text, 'error_name'),
  },
  {
    path: 'services/policy/src/engine.rs',
    origin: 'the Policy Engine',
    what: 'the rules the Policy Engine decides under, which the console and your audit chain name',
    read: (text) => constsInModule(text, 'clause'),
  },
  {
    path: 'services/policy/src/attest.rs',
    origin: 'the Policy Engine, on an approval',
    what: 'the clause ids an attestation is refused under',
    // `clause: "AT-5",` -- a struct field rather than a constant, so it is
    // read as one instead of being folded into the rule above.
    read: (text) => [...text.matchAll(/^\s*clause: "([^"]+)",$/gm)].map((m) => m[1]),
  },
  {
    path: 'services/policy/src/category.rs',
    origin: 'the decision API',
    what: "the refusal categories a decision's `refusal_category` carries",
    read: (text) => constsInModule(text, 'name'),
  },
];

/** Every `pub const X: &str = "value";` inside `pub mod <name> { ... }`.
 *
 * The module is found by its header and closed by the first line that is `}`
 * at the header's own indentation -- the two modules read here are top level
 * and hold only constants, and a nested `mod` inside one would end the span
 * early rather than absorb it. A module that is not there yields nothing,
 * which is what the empty check below turns into a halt. */
function constsInModule(text, name) {
  const lines = text.split('\n');
  const open = lines.findIndex((line) => line.trimEnd() === `pub mod ${name} {`);
  if (open === -1) return [];
  const out = [];
  for (let i = open + 1; i < lines.length; i += 1) {
    if (lines[i] === '}') break;
    const match = /^\s*pub const [A-Z0-9_]+: &str = "([^"]+)";$/.exec(lines[i]);
    if (match !== null) out.push(match[1]);
  }
  return out;
}

const onboarding = onboardingDocs();
if (!onboarding.some((doc) => doc.path === SUPPORT_DOC)) {
  fail(
    `SupportDocNotServed: ${SUPPORT_DOC} is not in the served set.\n` +
      '  explain_refusal serves rows out of its table; without it the tool has no table at all.',
  );
}
const supportMarkdown = onboarding.find((doc) => doc.path === SUPPORT_DOC).markdown;
if (!supportMarkdown.includes(REFUSAL_TABLE_MARKER)) {
  fail(
    `RefusalTableUnmarked: ${SUPPORT_DOC} carries no ${REFUSAL_TABLE_MARKER}.\n` +
      '  The table is located by that marker and not by a heading, so a document that stopped\n' +
      '  publishing it must stop the build rather than serve an empty table.',
  );
}

const emitters = REFUSAL_EMITTERS.map((emitter) => {
  const names = [...new Set(emitter.read(readSource(emitter.path)))].sort();
  if (names.length === 0) {
    fail(
      `RefusalEmitterEmpty: ${emitter.path} yielded no refusal name.\n` +
        '  Either the module was renamed or the spelling changed. An empty emitter set makes\n' +
        "  explain_refusal's completeness comparison pass by having nothing to compare, which is\n" +
        '  the one outcome worse than a red one.',
    );
  }
  // The customer reads `origin`, never `path`: the path is where THIS build reads the names, a
  // file of ours no customer has, so it stays in the build and out of the package.
  return { origin: emitter.origin, what: emitter.what, names };
});

writeFileSync(
  join(outDir, 'docs-source.ts'),
  '// GENERATED by scripts/embed-guide.mjs from docs/onboarding. Do not edit.\n' +
    '// Gitignored and rewritten on every build; src/docs.test.ts asserts each of\n' +
    '// these documents is still the file on disk, so a stale copy cannot survive a run.\n' +
    'export interface OnboardingDoc { readonly path: string; readonly markdown: string }\n' +
    `export const ONBOARDING_DOCS: readonly OnboardingDoc[] = ${JSON.stringify(onboarding)};\n` +
    '/** Documents in that directory this package deliberately does not serve, and why. */\n' +
    `export const ONBOARDING_NOT_SERVED: Readonly<Record<string, string>> = ${JSON.stringify(ONBOARDING_NOT_SERVED)};\n` +
    `export const ONBOARDING_DIR = ${JSON.stringify(ONBOARDING_DIR.split('\\').join('/'))};\n` +
    `export const SUPPORT_DOC_PATH = ${JSON.stringify(SUPPORT_DOC)};\n` +
    `export const REFUSAL_TABLE_MARKER = ${JSON.stringify(REFUSAL_TABLE_MARKER)};\n` +
    '/** Where a refusal name is minted, and every name that source mints. */\n' +
    'export interface RefusalEmitter { readonly origin: string; readonly what: string; readonly names: readonly string[] }\n' +
    `export const REFUSAL_EMITTERS: readonly RefusalEmitter[] = ${JSON.stringify(emitters)};\n`,
  'utf8',
);

process.stderr.write(
  `embed-guide: ${onboarding.length} onboarding documents ` +
    `(${Object.keys(ONBOARDING_NOT_SERVED).length} withheld), ` +
    `${emitters.reduce((n, e) => n + e.names.length, 0)} refusal names from ${emitters.length} sources\n`,
);
